/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme.zaduzenje;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author filipjevtovic
 */
public class DodajZaduzenjeForma extends javax.swing.JFrame {

    /**
     * Creates new form DodajPozajmicu
     */
    public DodajZaduzenjeForma() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDatumZaduzenja = new javax.swing.JTextField();
        jTextFieldDatumRazduzenja = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldImePrezime = new javax.swing.JTextField();
        jButtonPretraziClana = new javax.swing.JButton();
        jButtonResetujClana = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClanovi = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNazivKnjige = new javax.swing.JTextField();
        jButtonPretraziKnjigu = new javax.swing.JButton();
        jButtonResetujKnjigu = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableKnjige = new javax.swing.JTable();
        jButtonDodajPozajmicu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dodaj Zaduzenje");

        jLabel1.setText("Datum zaduzenja (dd/MM/yyyy):");

        jLabel2.setText("Datum razduzenja (dd/MM/yyyy):");

        jLabel3.setText("Ime i Prezime clana:");

        jButtonPretraziClana.setText("Pretrazi");

        jButtonResetujClana.setText("Resetuj");

        jTableClanovi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableClanovi);

        jLabel4.setText("Naziv knjige:");

        jButtonPretraziKnjigu.setText("Pretrazi");

        jButtonResetujKnjigu.setText("Resetuj");

        jTableKnjige.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableKnjige);

        jButtonDodajPozajmicu.setText("Dodaj");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldDatumZaduzenja, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                            .addComponent(jTextFieldDatumRazduzenja)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNazivKnjige, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButtonPretraziKnjigu)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButtonResetujKnjigu))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldImePrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonPretraziClana)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonResetujClana))))
                    .addComponent(jScrollPane2)
                    .addComponent(jButtonDodajPozajmicu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldDatumZaduzenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldDatumRazduzenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldImePrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPretraziClana)
                    .addComponent(jButtonResetujClana))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldNazivKnjige, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPretraziKnjigu)
                    .addComponent(jButtonResetujKnjigu))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonDodajPozajmicu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodajPozajmicu;
    private javax.swing.JButton jButtonPretraziClana;
    private javax.swing.JButton jButtonPretraziKnjigu;
    private javax.swing.JButton jButtonResetujClana;
    private javax.swing.JButton jButtonResetujKnjigu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableClanovi;
    private javax.swing.JTable jTableKnjige;
    private javax.swing.JTextField jTextFieldDatumRazduzenja;
    private javax.swing.JTextField jTextFieldDatumZaduzenja;
    private javax.swing.JTextField jTextFieldImePrezime;
    private javax.swing.JTextField jTextFieldNazivKnjige;
    // End of variables declaration//GEN-END:variables

    
    
    public JButton getjButtonDodajPozajmicu() {
        return jButtonDodajPozajmicu;
    }

    public JButton getjButtonPretraziClana() {
        return jButtonPretraziClana;
    }

    public JButton getjButtonPretraziKnjigu() {
        return jButtonPretraziKnjigu;
    }

    public JButton getjButtonResetujClana() {
        return jButtonResetujClana;
    }

    public JButton getjButtonResetujKnjigu() {
        return jButtonResetujKnjigu;
    }

    public JTable getjTableClanovi() {
        return jTableClanovi;
    }

    public JTable getjTableKnjige() {
        return jTableKnjige;
    }

    public JTextField getjTextFieldDatumZaduzenja() {
        return jTextFieldDatumZaduzenja;
    }

    public JTextField getjTextFieldDatumRazduzenja() {
        return jTextFieldDatumRazduzenja;
    }

    public JTextField getjTextFieldNazivKnjige() {
        return jTextFieldNazivKnjige;
    }

    public JTextField getjTextFieldImePrezime() {
        return jTextFieldImePrezime;
    }

    public void addBtnPretraziClanaActionListener(ActionListener actionListener) {
        jButtonPretraziClana.addActionListener(actionListener);
    }

    public void addBtnResetujClanoveActionListener(ActionListener actionListener) {
        jButtonResetujClana.addActionListener(actionListener);
    }

    public void addBtnPretraziKnjiguActionListener(ActionListener actionListener) {
        jButtonPretraziKnjigu.addActionListener(actionListener);
    }

    public void addBtnResetujKnjigeActionListener(ActionListener actionListener) {
        jButtonResetujKnjigu.addActionListener(actionListener);
    }

    public void dodajAddActionListener(ActionListener actionListener) {
        jButtonDodajPozajmicu.addActionListener(actionListener);
    }
}
